### PR TITLE
Updating README.md file to make it more understandable

### PR DESCRIPTION
**Pull request by faizankshaikh**

### CODE REVIEW

**Comment by oswaldoludwig** [comment]
Hi, I would like to merge your PR, but the system doesn't enable it. Please see the following message: "This branch has conflicts that must be resolved". It is probably due to my last commit (after your PR).

**Comment by faizankshaikh** [comment]
Updated. No conflicts now!

**Comment by oswaldoludwig** [comment]
Hi, true, no conflicts, but now we have some issues, if you compile the file (pressing the button "view") you will see something like this:

"  <<<<<<< HEAD
4. This model uses the Eigenvalue Decay regularizer, if Keras is already installed, check if you have this regularizer, if don't have it, update Keras to have Eigenvalue Decay: sudo pip install git+git://github.com/fchollet/keras.git --upgrade

4) This model uses the Eigenvalue Decay regularizer, if Keras is already installed, check if you have this regularizer, if you don't have it, update Keras to have Eigenvalue Decay: sudo pip install git+git://github.com/fchollet/keras.git --upgrade

```
                        f80f0ce758a70be17e198a1a06b23886889fdf07

Run “HumanActionRecognition.py” to train the deep model and create the submission file with the estimated classes for the test data. To run in GPU you can call the code like this: THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32,exception_verbosity=high python HumanActionRecognition.py "
```

Could you please check this PR?

Thanks in advance,

Oswaldo

**Comment by faizankshaikh** [comment]
Oh. Let me do this again

**Pull request closed without merging**
